### ISSUE TITLE
Cheat Sheet v. GB bug

### ISSUE THREAD

**Issue by BelphSenpai** [JavidPack/CheatSheet#1]
version 0.7.2 

it happens when trying to use the hostile npc butcher, havent tested other functions yet 
![image](https://user-images.githubusercontent.com/29332430/27002371-6fadd260-4dd8-11e7-9465-f28bcea4365d.png)

Enabled.json report:

[
  "AutoTrash",
  "Bluemagic",
  "BossChecklist",
  "SolutionsMod",
  "imkSushisMod",
  "AlchemistNPC",
  "JoostMod",
  "MagicStorage",
  "CalamityMod",
  "RecipeBrowser",
  "CheatSheet",
  "Tremor"
]

**Comment by JavidPack** [comment]
Reopen if persists, could not replicate.
