### ISSUE TITLE
Paint Tool not appearing?

### ISSUE THREAD

**Issue by RecklessJames** [JavidPack/CheatSheet#18]
Isnt there supposed to be a Paint Tool feature or something? People keep talkin' bout it, but ME NO SEE!

**Comment by JavidPack** [comment]
Here is a video; https://gfycat.com/wellmadeveneratedbufeo

If you don't see it, maybe click on the gear icon and see if it is hidden or not.

**Comment by RecklessJames** [comment]
oops I got it now, apparently I was confusing this with an entirely different mod with a similar looking toolbar... I just now found it haha.  thanks!
