### ISSUE TITLE
Tile editing tools break for screens bigger than 1080p

### ISSUE THREAD

**Issue by Joeyrsp** [JavidPack/CheatSheet#2]
The grabbed area does not line up with what I select visually and when I use the brush it applies it offset from where I am clicking. I am using 2560x1440p.
For extra info (that probably isn't useful), Hero's freecam also does the same thing.

![cut](https://user-images.githubusercontent.com/29254543/30876043-b7abb9a0-a338-11e7-8416-637eab815dbb.PNG)
![paste](https://user-images.githubusercontent.com/29254543/30876111-f96110d4-a338-11e7-9041-d4709479546e.PNG)

**Comment by JavidPack** [comment]
This works since a 9010a2a8ff75bb29a3357403c3044e720c451a61
