### ISSUE TITLE
Cheat sheet build error

### ISSUE THREAD

**Issue by wrath3k** [JavidPack/CheatSheet#55]
mod wont show up in the mods list. however it does show up in the mod sources (when i added it) but runs into an error when building it
![image_2021-04-14_210517](https://user-images.githubusercontent.com/70595095/114803475-269ccc80-9d65-11eb-93d2-f39a072f99a5.png)

**Comment by JavidPack** [comment]
Post client.log. kinda looks like you aren't on three latest tmodloader.
