### ISSUE TITLE
Typing "pi" into the NPC search box crashes the game on Linux

### ISSUE THREAD

**Issue by flarn2006** [JavidPack/CheatSheet#59]
Whenever I type the letters `pi` into the NPC Browser search box, it displays the search results for a split second but then the game crashes with an error dialog. At least [one other person](https://www.reddit.com/r/Terraria/comments/hz3i8b/tml_npc_that_crashes_the_game_upon_being_viewed/) has encountered this exact issue; they and I are both using Linux so that likely has something to do with it.

[client.log](https://github.com/JavidPack/CheatSheet/files/7866054/client.log)

**Comment by JavidPack** [comment]
It seemed you fixed this according to your issue on the tmodloader github.

**Comment by flarn2006** [comment]
Yep, meant to post this here but forgot.
