### ISSUE TITLE
Incorrect Export path for Paint Tool on Linux

### ISSUE THREAD

**Issue by Qunas101** [JavidPack/CheatSheet#91]
When exporting with the paint tool, CheatSteet_PaintTools.txt contains this text:
```
/home/*username*/.local/share/Terraria/tModLoader\CheatSheet_PaintTools_1.json
/home/*username*/.local/share/Terraria/tModLoader\CheatSheet_PaintTools_2.json
```
Notice how the last slash is reverse, like it is on Windows.

And indeed if I check the Terraria folder, I can find those files there:

![зображення](https://github.com/user-attachments/assets/c2b63937-72c8-4709-bf9b-fea2ee992729)

I'm not sure if it is dangerous or anything malicious could be done with it (probably not), but I guess it could be inconvenient for the 3 people who might use it

**Comment by JavidPack** [comment]
Thanks for the report, shouldn't be hard to fix once I find time.
